# https://taskfile.dev

version: '3'

tasks:
  run:
    deps: [build]
    dir: backend
    cmds:
      - cmd: poetry run uvicorn backend.__main__:app --reload
        ignore_error: true

  clean:
    cmds:
      - task: clean-frontend

  clean-frontend:
    dir: frontend
    cmds: 
      - rm -r build

  build:
    cmds:
      - task: build-frontend

  build-frontend:
    dir: frontend
    cmds: 
      - npm run build
