# https://taskfile.dev

version: '3'

tasks:
  # Main commands 
  run:
    desc: Run project.
    dir: backend
    cmds:
      - cmd: poetry run uvicorn backend.__main__:app
        ignore_error: true

  dev-run:
    desc: Run project in development mode.
    dir: backend
    cmds:
      - cmd: poetry run uvicorn backend.__main__:app --reload
        ignore_error: true

  build:
    desc: Build project.
    cmds:
      - task: build-frontend

  build-frontend:
    desc: Build frontend.
    dir: frontend
    cmds: 
      - npm run build

  install:
    desc: Install project dependencies.
    cmds:
      - task: install-frontend
      - task: install-backend

  install-frontend:
    desc: Install frontend dependencies.
    dir: frontend
    cmds:
      - npm install

  install-backend:
    desc: Install backend dependencies.
    dir: backend
    cmds: 
      - poetry install

  # Additional commands
  format:
    desc: Formats project source code. 
    cmds: 
      - task: format-backend
  
  format-backend:
    desc: Formats backend source code.
    dir: backend
    cmds: 
      - poetry run autopep8 -i -r -a -a -a backend/
      - poetry run isort .

  setup-pypy:
    desc: Setup PyPy in Poetry shell.
    dir: backend
    cmds:
      - cmd: poetry env remove python
        ignore_error: true
      - poetry env use pypy
